/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#4ae176",
        "primary": "#3525cd",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-tertiary-container": "#ffd2be",
        "outline": "#777587",
        "tertiary": "#7e3000",
        "primary-fixed-dim": "#c3c0ff",
        "surface-dim": "#dcd8e5",
        "inverse-primary": "#c3c0ff",
        "surface-container-highest": "#e4e1ee",
        "on-tertiary-fixed": "#351000",
        "surface-container-low": "#f5f2ff",
        "on-primary-container": "#dad7ff",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "inverse-on-surface": "#f3effc",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdbcc",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#6bff8f",
        "on-secondary-fixed": "#002109",
        "background": "#fcf8ff",
        "on-secondary-container": "#007432",
        "surface-bright": "#fcf8ff",
        "tertiary-fixed-dim": "#ffb695",
        "on-primary-fixed": "#0f0069",
        "inverse-surface": "#302f39",
        "error-container": "#ffdad6",
        "outline-variant": "#c7c4d8",
        "secondary": "#006e2f",
        "on-secondary-fixed-variant": "#005321",
        "on-error-container": "#93000a",
        "surface-container-high": "#eae6f4",
        "on-background": "#1b1b24",
        "surface-container": "#f0ecf9",
        "tertiary-container": "#a44100",
        "primary-fixed": "#e2dfff",
        "secondary-container": "#6bff8f",
        "on-tertiary": "#ffffff",
        "on-surface": "#1b1b24",
        "on-error": "#ffffff",
        "surface-tint": "#4d44e3",
        "primary-container": "#4f46e5",
        "surface-variant": "#e4e1ee",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#464555",
        "surface": "#fcf8ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "16px",
        "container-padding": "24px",
        "xl": "32px",
        "unit": "4px",
        "xs": "4px",
        "sm": "8px",
        "table-cell-padding": "12px 16px",
        "lg": "24px"
      },
      "fontFamily": {
        "inter": ["Inter", "sans-serif"],
        "label-caps": ["Inter"],
        "number-lg": ["Inter"],
        "h3": ["Inter"],
        "h2": ["Inter"],
        "number-display": ["Inter"],
        "h1": ["Inter"],
        "body-sm": ["Inter"],
        "body-base": ["Inter"]
      },
      "fontSize": {
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "number-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "h3": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "h2": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "number-display": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "h1": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-base": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
